config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  get 'messages/webhook', to: 'messages#webhook'
  post 'messages/webhook', to: 'messages#incoming'

  # Force login endpoint
  get '/force_login/:name', to: 'users#force_login'

  # Facebook oauth endpoint
  get '/login_success', to: 'users#login_success'

  # User newsfeed and profile stuff
  get '/newsfeed', to: 'users#newsfeed', as: :user_newsfeed
  get '/friends', to: 'users#friends', as: :user_friends
  get '/users/:user_id/activity', to: 'users#activity', as: :user_activity

  get '/users/:user_id/goals', to: 'users#goals', as: :user_goals
  post '/new_goal', to: 'users#new_goal', as: :new_goal
  post '/goal/:goal_id/encourage', to: 'users#encourage', as: :encourage
  get '/goal/:goal_id/log', to: 'users#log_goal', as: :log_goal

  get '/users/:user_id/availability', to: 'users#availability', as: :user_availability
  get '/edit_availability', to: 'users#edit_availability', as: :edit_availability
  post '/set_availability', to: 'users#set_availability', as: :set_availability

  get '/users/:user_id/interests', to: 'users#interests', as: :user_interests
  get '/edit_interests', to: 'users#edit_interests', as: :edit_interests
  post '/set_interests', to: 'users#set_interests', as: :set_interests

  # Invites
  get '/invites/new', to: 'invites#new', as: :new_invite
  post '/invites/create', to: 'invites#create', as: :create_invite
  get '/invites/upcoming', to: 'invites#upcoming', as: :upcoming_invites
  get '/invites/respond', to: 'invites#respond', as: :respond_invite
  post '/invites/:id/accept', to: 'invites#accept', as: :accept_invite
  post '/invites/:id/decline', to: 'invites#decline', as: :decline_invite

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  layout 'webview'
  before_action :load_current_user, except: [:new, :respond]

  def new
    load_fb_user('/invites/new')
  end

  def upcoming
    @invites = @current_user.invitations.chronological
  end

  def respond
    load_invite_user('/invites/respond')
    @existing_response = InvitationResponse.where({user: @current_user, invitation: @invite}).first
    render 'respond', layout: 'webview_no_menu'
    if !@existing_response.present? && @current_user.id != @invite.user.id
      InvitationResponse.create({user: @current_user, invitation: @invite, response: 'seen'})
    end
  end

  def accept
    @invite = Invitation.find(params[:id])
    response = InvitationResponse.find_or_create_by({user: @current_user, invitation: @invite})
    response.update_attributes({response: 'accepted'})
    Activity.create({user: @current_user,
                     text: "#{@current_user.first_name} is going to an event: #{@invite.what}!",
                     time: @invite.when, location: @invite.where})
  end

  def decline
    @invite = Invitation.find(params[:id])
    response = InvitationResponse.find_or_create_by({user: @current_user, invitation: @invite})
    response.update_attributes({response: 'declined'})
    response.save!
  end

  def create
    unless params[:what].present? && params[:details].present? &&
           params[:where].present? && params[:when].present?
      flash[:error] = 'Please fill out all the fields'
      render 'new'
    else
      invite = Invitation.create({user: @current_user, what: params[:what],
                         details: params[:details], where: params[:where],
                         when: params[:when]})
      Activity.create({user: @current_user,
                       text: "#{@current_user.first_name} made a new event: #{params[:what]}!",
                       time: params[:when], location: params[:where]})
      unless session[:force_mode]
        receiver = GetStartedReceiver.new(@current_user)
        receiver.send_invite_card(invite)
      end
      render 'users/login_success', layout: 'bare'
    end
  end

  private

  def load_invite_user(route)
    if session[:force_mode]
      @current_user = User.find(session[:current_user])
      @invite = Invitation.find(params[:id])
      return
    end
    return if dev_mode?
    data = Rack::Utils.parse_nested_query(params[:state]).deep_symbolize_keys
    @invite = Invitation.find(data[:invite_id])
    fb_service = FacebookProfileService.new(params[:code], route)
    @current_user = fb_service.update_profile
    session[:current_user] = @current_user.id
  end

end

app/views/invites/_invite_tabs.html.erb
<style>
  #InviteMenu > .item {
    min-width: 50%;
  }

  #InviteMenu > .item > span {
    margin: auto;
  }
</style>

<div id="InviteMenu" class="ui blue secondary pointing menu">
  <a href="<%= new_invite_path %>" class="item <%= 'active' if current_page?(new_invite_path) %>">
    <span>Create an Invite</span>
  </a>
  <a href="<%= upcoming_invites_path %>" class="item <%= 'active' if current_page?(upcoming_invites_path) %>">
    <span>Your Invites</span>
  </a>
</div>
<% if flash[:notice] %>
  <div class="ui message green" style="text-align: center">
    <i class="close icon"></i>
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="ui message red" style="text-align: center">
    <i class="close icon"></i>
    <%= flash[:error] %>
  </div>
<% end %>

<script>
  $('.message .close').on('click', function() {
    $(this).closest('.message').transition('fade');
  });
</script>

app/views/invites/_response_list.html.erb
<div id="InviteResponses" class="ui styled fluid accordion">
  <div class="title">
    <i class="dropdown icon"></i>
    <span style="color: #444"><i class="users icon"></i> Who's coming</span>
  </div>
  <div class="content">
    <div id="InviteResponsesList" class="ui list">
      <% responses.each do |response| %>
        <div class="item">
          <img src="<%= response.user.picture_url %>" class="ui avatar image" />
          <span><%= response.user.full_name %></span>
          <% if response.response == 'declined' %>
            <div class="ui lightgrey horizontal label">Declined</div>
          <% elsif response.response == 'accepted' %>
            <div class="ui green horizontal label">Accepted</div>
          <% else %>
            <div class="ui basic horizontal label">Seen</div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#InviteResponses').accordion();
</script>

app/views/invites/new.html.erb
<%= render 'invites/invite_tabs' %>

<style>
  #NewInvite > .inviteField {
    margin-bottom: .75rem;
  }

  #NewInvite > .inviteField input {
    width: 17.6rem;
  }

  #NewInvite > .inviteField > .label {
    width: 5rem;
  }

  #NewInvite > .inviteField > .dropdown {
    width: 17.5rem;
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }

  #NewInvite > .inviteSubmit {
    width: 100%;
  }

</style>
<form id="NewInvite" class="ui form" action="/invites/create" method="post">
  <!-- What -->
  <div class="ui labeled input inviteField" style="margin-bottom:14px;">
    <div class="ui label">What</div>
    <div class="ui search">
      <div class="ui icon input">
        <input name="what" class="prompt" type="text" placeholder="Select an activity, e.g. Tennis">
        <i class="search icon"></i>
      </div>
    </div>
  </div>

  <!-- Details -->
  <div class="ui labeled input inviteField">
    <div class="ui label">Details</div>
    <input name="details" type="text" placeholder="e.g. Let's burn some calories!">
  </div>

  <!-- Where -->
  <div class="ui labeled input inviteField">
    <div class="ui label">Where</div>
    <input name="where" type="text" placeholder="e.g. 5000 Forbes Ave.">
  </div>

  <!-- When -->
  <div class="ui labeled input inviteField">
    <div class="ui label">When</div>
    <input name="when" type="text" placeholder="e.g. Friday at 8pm, anytime, etc">
  </div>

  <!-- Submit -->
  <button type="submit" class="ui fluid positive inviteSubmit button">Create</button>
</form>

<script>
  $('select.dropdown').dropdown();
  $('.ui.search')
    .search({
      source: <%== FormFieldData::ACTIVITIES.map{ |activity| {title: activity} }.to_json %>
    });
</script>

app/views/invites/respond.html.erb
<style>
  #RespondInvite .responseButtons {
    display: flex;
    justify-content: space-between;
  }

  #RespondInvite .responseButtons > a {
    width: 47%;
  }

  #RespondInvite > .content > .mainHeader {
    font-size: 1.1rem;
  }

  #RespondInvite > .content > .location {
    margin-top: .15rem;
  }

  #RespondInvite > .content .icon {
    margin-right: 1px;
    margin-bottom: .25rem;
  }
</style>

<div id="RespondInvite"  class="ui fluid card">
  <div class="content">
    <div class="header mainHeader">
      <%== @invite.what %>
      <span style="float: right"><%== @invite.when %></span>
    </div>
  </div>
  <div class="content">
    <div class="ui sub header"><i class="user icon"></i> <%== @invite.user.full_name %></div>
    <div class="ui sub header location"><i class="marker icon"></i> <%== @invite.where %></div>
    <p><i class="info icon"></i> <%== @invite.details %></p>

    <%= render 'invites/response_list', responses: @invite.invitation_responses.alphabetical %>

    <% showa = (@existing_response.present? && @existing_response.response == 'accepted') %>
    <% showd = (@existing_response.present? && @existing_response.response == 'declined') %>
    <div class="ui green message" style="text-align: center; <%== 'display: none' unless showa %>">Invitation Accepted!</div>
    <div class="ui lightgrey message" style="text-align: center; <%== 'display: none' unless showd %>">Invitation Declined. Maybe next time!</div>

    <% if @invite.user.id != @current_user.id && (@existing_response.nil? || !(['accepted', 'declined'].include?(@existing_response.response)))  %>
      <div class="responseButtons" style="margin-top: .75rem">
        <a class="ui positive button" onclick="inviteAccept();">Accept</a>
        <a class="ui lightgrey button" onclick="inviteDeclined();">Decline</a>
      </div>
    <% end %>
  </div>
</div>

<!-- if no fb_messenger_id -->
<div id="LearnAboutUs" class="ui accordion">
  <div class="title">
   <i class="dropdown icon"></i> What's Let's Thryve?
  </div>

  <div class="content">
    <p style="color: grey;">
      Let's Thryve is a Messenger bot that helps you find friends to exercise and hangout with.
      Click 'Send to Messenger' below to start using the bot!
    </p>
    <div class="ui right aligned container fb-send-to-messenger"
      style="margin-right: 0 !important;"
      messenger_app_id="<%= ENV['FB_APP_ID'] %>"
      page_id="<%= ENV['FB_PAGE_ID'] %>"
      data-ref="MessagedUs"
      color="white"
      size="large">
    </div>
  </div>
</div>

<script>
  var thryveProfileImage = '<%= @current_user.picture_url %>';

  window.fbAsyncInit = function() {
    FB.init({
      appId: "<%= ENV['FB_APP_ID'] %>",
      xfbml: true,
      version: "v2.6"
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) { return; }
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  $('#LearnAboutUs').accordion();

  function inviteAccept(){
    var thryveListItem = '<div class="item">' +
        '<img src="' + thryveProfileImage + '" class="ui avatar image" />' +
        '<span>You</span>' +
        '<div class="ui green horizontal label">Accepted</div>' +
      '</div>';

    $.post("<%= accept_invite_path(@invite) %>");
    $('#InviteResponsesList').prepend(thryveListItem);
    $('.green.message').show();
    $('.responseButtons').hide();
  }

  function inviteDeclined(){
    var thryveListItem = '<div class="item">' +
        '<img src="' + thryveProfileImage + '" class="ui avatar image" />' +
        '<span>You</span>' +
        '<div class="ui lightgrey horizontal label">Declined</div>' +
      '</div>';

    $.post("<%= decline_invite_path(@invite) %>");
    $('#InviteResponsesList').prepend(thryveListItem);
    $('.lightgrey.message').show();
    $('.responseButtons').hide();
  }
</script>

app/views/invites/upcoming.html.erb
<%= render 'invites/invite_tabs' %>

<style>
  #UpcomingInvites > .content > .mainHeader {
    font-size: 1.1rem;
  }

  #UpcomingInvites > .content > .location {
    margin-top: .15rem;
  }

  #UpcomingInvites > .content .icon {
    margin-right: 1px;
    margin-bottom: .25rem;
  }
</style>

<% unless @invites.present? %>
  <div style="text-align: center" class="ui grey message">
    There are no invitations to show yet! Maybe you should invite someone :)
  </div>
<% end %>
<% @invites.each do |invite| %>
  <div id="UpcomingInvites"  class="ui fluid card">
    <div class="content">
      <div class="header mainHeader">
        <%= invite.what %>
        <span style="float: right"><%= invite.when %></span>
      </div>
    </div>
    <div class="content">
      <div class="ui sub header"><i class="user icon"></i> <%= invite.user.full_name %></div>
      <div class="ui sub header location"><i class="marker icon"></i> <%= invite.where %></div>
      <p><i class="info icon"></i> <%= invite.details %></p>

      <%= render 'invites/response_list', responses: invite.invitation_responses.alphabetical %>
    </div>
  </div>
<% end %>