config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  get 'messages/webhook', to: 'messages#webhook'
  post 'messages/webhook', to: 'messages#incoming'

  # Force login endpoint
  get '/force_login/:name', to: 'users#force_login'

  # Facebook oauth endpoint
  get '/login_success', to: 'users#login_success'

  # User newsfeed and profile stuff
  get '/newsfeed', to: 'users#newsfeed', as: :user_newsfeed
  get '/friends', to: 'users#friends', as: :user_friends
  get '/users/:user_id/activity', to: 'users#activity', as: :user_activity

  get '/users/:user_id/goals', to: 'users#goals', as: :user_goals
  post '/new_goal', to: 'users#new_goal', as: :new_goal
  post '/goal/:goal_id/encourage', to: 'users#encourage', as: :encourage
  get '/goal/:goal_id/log', to: 'users#log_goal', as: :log_goal

  get '/users/:user_id/availability', to: 'users#availability', as: :user_availability
  get '/edit_availability', to: 'users#edit_availability', as: :edit_availability
  post '/set_availability', to: 'users#set_availability', as: :set_availability

  get '/users/:user_id/interests', to: 'users#interests', as: :user_interests
  get '/edit_interests', to: 'users#edit_interests', as: :edit_interests
  post '/set_interests', to: 'users#set_interests', as: :set_interests

  # Invites
  get '/invites/new', to: 'invites#new', as: :new_invite
  post '/invites/create', to: 'invites#create', as: :create_invite
  get '/invites/upcoming', to: 'invites#upcoming', as: :upcoming_invites
  get '/invites/respond', to: 'invites#respond', as: :respond_invite
  post '/invites/:id/accept', to: 'invites#accept', as: :accept_invite
  post '/invites/:id/decline', to: 'invites#decline', as: :decline_invite

end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :friends, through: :friendships, source: :friend
  has_many :activities
  has_many :goals
  has_many :invitations
  has_many :invitation_responses
end

# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  fb_messenger_id   :string
#  fb_profile_id     :string
#  first_name        :string
#  full_name         :string
#  picture_url       :string
#  ignore            :boolean          default(FALSE)
#  last_message_sent :string
#  interests         :string
#  availability      :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_users_on_fb_messenger_id  (fb_messenger_id)
#  index_users_on_fb_profile_id    (fb_profile_id)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'webview'
  before_action :load_current_user, except: [:force_login, :login_success, :newsfeed]
  before_action :load_user, only: [:activity, :goals, :interests, :availability]

  def force_login
    session[:force_mode] = true
    session[:current_user] = User.where(first_name: params[:name].capitalize).first.id
    redirect_to user_newsfeed_url
  end

  def login_success
    load_fb_user('/login_success', true)
    receiver = GetStartedReceiver.new(@current_user)
    receiver.initial_preferences
    render 'login_success', layout: 'bare'
  end

  def newsfeed
    load_fb_user('/newsfeed')
    @show_all = true if params[:show_all]
    if @show_all
      @activities = Activity.except_user(@current_user).chronological
    else
      @activities = Activity.for_user_friends(@current_user).chronological
    end
  end

  def friends
    @friends = @current_user.friends.order(:full_name)
  end

  def activity
    @activities = Activity.for_user(@user).chronological
  end

  def goals
    @goals = Goal.for_user(@user).by_state.chronological
  end

  def new_goal
    Goal.create({user: @current_user, text: params[:goalText], state: 3})
    Activity.create({user: @current_user,
                     text: "#{@current_user.first_name} made a goal: #{truncate(params[:goalText], length: 70, separator: ' ')}",
                     time: now_string})
    redirect_to user_goals_url(@current_user)
  end

  def encourage
    @goal = Goal.find(params[:goal_id])
    GoalEncouragement.create({user: @current_user, goal: @goal, text: params[:message]})
    Activity.create({user: @goal.user, picture_url_override: @current_user.picture_url,
                     text: "#{@current_user.first_name} encouraged #{@goal.user.first_name}: #{truncate(params[:message], length: 70, separator: ' ')}",
                     time: now_string})
    redirect_to :back
  end

  def log_goal
    goal = Goal.find(params[:goal_id])
    goal.update_attributes(state: params[:state].to_i)
    action = ['didn\'t achieve their goal', 'tried to achieve their goal', 'achieved their goal!']
    Activity.create({user: @current_user,
                     text: "#{@current_user.first_name} #{action[params[:state].to_i]}: #{truncate(goal.text, length: 70, separator: ' ')}",
                     time: now_string})

    if params[:state].to_i == 0
      flash[:notice] = 'Logged! Better luck next time!'
    elsif params[:state].to_i == 1
      flash[:notice] = 'Logged! Good try, but, stick to it next time!'
    elsif params[:state].to_i == 2
      flash[:notice] = 'Logged! Nice job, keep it up!'
    end
    redirect_to user_goals_path(@current_user)
  end

  def availability
    @edit_mode = false
    if @user.availability.present?
      @availability = JSON.parse(@user.availability).map(&:symbolize_keys)
    else
      @availability = []
    end
  end

  def edit_availability
    @edit_mode = true
    render 'availability'
  end

  def set_availability
    availability = []
    (0...5).each do |i|
      availability.append({day: params[:free_day][i], time: params[:free_time][i]})
    end

    if params[:free_day].include?('') || params[:free_time].include?('')
      flash[:error] = 'Please set the top 5 times you\'re free'
      @edit_mode = true
      render 'availability'
    else
      @current_user.update_attributes(availability: availability.to_json)
      flash[:notice] = 'Your availability was saved'
      redirect_to user_availability_url(@current_user)
    end
  end

  def interests
    @edit_mode = false
    if @user.interests.present?
      @interests = JSON.parse(@user.interests).symbolize_keys
    else
      @interests = {exercises: ['None selected'], hangouts: ['None selected'], oncampus: ['None selected']}
    end
  end

  def edit_interests
    @edit_mode = true
    render 'interests'
  end

  def set_interests
    interests = {
      exercises: params[:exercises],
      hangouts: params[:hangouts],
      oncampus: params[:oncampus]
    }.to_json

    unless params[:exercises] && params[:hangouts] && params[:oncampus]
      flash[:error] = "Select at least one interest in each category."
      @edit_mode = true
      render 'interests'
    else
      @current_user.update_attributes(interests: interests)
      flash[:notice] = 'Your interests were saved'
      redirect_to user_interests_url(@current_user)
    end
  end

  private

  def load_user
    @user = User.find(params[:user_id])
  end

  def now_string
    DateTime.now.strftime('On %b %e, %Y')
  end
end

app/views/users/_activity_list.html.erb
<style>
  #ActivityList .entry {
    display: flex;
    padding-bottom: .5rem;
    margin-bottom: .25rem;
  }
</style>


<div id="ActivityList">
  <% unless @activities.present? %>
    <div style="text-align: center" class="ui lightgrey message">There are no activities yet! <br />Go Thryve together!</div>
  <% end %>
  <% @activities.each do |activity| %>
    <div class="entry">
      <img class="ui avatar image" src="<%= activity.picture_url_override || activity.user.picture_url %>" style="margin-top: 5px">
      <p>
        <%== activity.text %><br />
        <span style="color: grey"><%== activity.time %>. <%== activity.location %></span>
      </p>
    </div>
  <% end %>
</div>

app/views/users/_invite_tabs.html.erb
<style>
  #UserProfileImage .smallPaddedColumn {
    padding: 14px 7px 7px 7px;
  }

  #UserProfileImage .image {
    width: 3rem;
    margin: auto;
  }

  #UserProfileImage .text {
    font-weight: bold;
    font-size: 1.2em;
  }

  #InviteMenu .item {
    text-align: center;
    padding-left: 33px;
    padding-right: 13px;
    min-width: 33.3%;

  }
</style>

<div id="UserProfileImage" class="ui grid">
  <div class="six wide column smallPaddedColumn">
    <img src="/assets/israel.png"
         class="ui medium circular image" />
  </div>
  <div class="ten wide column" style="padding-top: 25px">
    <span class="text">Israel Madueme</span>
  </div>
</div>
<div id="InviteMenu" class="ui blue secondary pointing menu">
  <%= link_to 'Create', user_activity_path(@user), class: 'active item' %>
  <%= link_to 'Upcoming', user_goals_path(@user), class: 'item' %>
  <%= link_to 'Past', user_interests_path(@user), class: 'item' %>
</div>

app/views/users/_profile_tabs.html.erb
<style>
  #UserProfileImage .smallPaddedColumn {
    padding: 14px 7px 7px 7px;
  }

  #UserProfileImage .image {
    width: 3rem;
    margin: auto;
  }

  #UserProfileImage .text {
    font-weight: bold;
    font-size: 1.2em;
  }

  #ProfileMenu .item {
    padding-left: 13px;
    padding-right: 13px;
  }
</style>

<% user = @user || @current_user %>
<div id="UserProfileImage" class="ui grid">
  <div class="six wide column smallPaddedColumn">
    <img src="<%= user.picture_url %>"
         class="ui medium circular image" />
  </div>
  <div class="ten wide column" style="padding-top: 25px">
    <span class="text"><%= user.full_name %></span>
  </div>
</div>
<div id="ProfileMenu" class="ui blue secondary pointing menu">
  <%= link_to 'Activity', user_activity_path(user), class: "item #{'active' if current_page?(user_activity_path(user))}" %>
  <%= link_to 'Goals', user_goals_path(user), class: "item #{'active' if current_page?(user_goals_path(user))}" %>
  <%= link_to 'Interests', user_interests_path(user), class: "item #{'active' if current_page?(user_interests_path(user)) || current_page?(edit_interests_path)}" %>
  <%= link_to 'Availability', user_availability_path(user), class: "item #{'active' if current_page?(user_availability_path(user)) || current_page?(edit_availability_path)}" %>
</div>
<% if flash[:notice] %>
  <div class="ui message green" style="text-align: center">
    <i class="close icon"></i>
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="ui message red" style="text-align: center">
    <i class="close icon"></i>
    <%= flash[:error] %>
  </div>
<% end %>

<script>
  $('.message .close').on('click', function() {
    $(this).closest('.message').transition('fade');
  });
</script>

app/views/users/_upcoming_events.html.erb
<%= render 'users/invite_tabs' %>


<div class="ui styled accordion">
  
  <div class="title">
    <i class="dropdown icon"></i>
    Level 2C
  </div>
  <div class="content">
   Level 2C Contents
  </div>
</div>

<script type="text/javascript">
  $('.ui.accordion')
  .accordion()
;
</script>

app/views/users/activity.html.erb
<%= render 'users/profile_tabs' %>

<%= render 'users/activity_list' %>

app/views/users/availability.html.erb
<%= render 'users/profile_tabs' %>
<style type="text/css">
  #webview-content .slot {
    margin-bottom: .5rem;
  }

  #webview-content .at {
    font-size: 1.2em;
    font-weight: bold;
    padding-top: 20px;
  }

  #webview-content .smallSidePadding {
    padding: 7px 4px 7px 4px;
  }

  #AvailabilityList .detail-day {
    font-size: 1em;
    font-weight: bold;
  }

  #AvailabilityList .detail-time {
    font-weight: bold;
  }

  #AvailabilityList .light-grey {
    background-color: #E1E2E3;
  }
</style>

<% unless @edit_mode %>
<div id="AvailabilityList">
  <% if @availability.empty? %>
    <div style="text-align: center" class="ui grey message">
      No availability has been set! Come on!
    </div>
  <% end %>

  <% @availability.each do |a| %>
    <div class="ui segment">
      <div class="ui equal width center aligned grid">
        <div class="centered column green">
          <span class="detail-day"><%= a[:day] %></span>
        </div>
        <div class="centered column">
          <span class="detail-time"><%= a[:time] %></span>
        </div>
      </div>
    </div>
  <% end %>

  <% if @user == @current_user %>
    <%= link_to 'Edit', edit_availability_path, class: 'ui lightgrey fluid button' %>
  <% end %>
</div>
<% else %>
<div id="webview-content">
  <div class="infoContainer">
    <p style="font-size: 1.1rem">When are the top 5 times that you're free?</p>
  </div>

  <form method="post" action="/set_availability" class="ui form">
    <div class="mainContainer">
      <div class="ui grid">
        <% 5.times do %>
          <div class="eight wide column smallSidePadding">
            <select name="free_day[]" class="ui dropdown daySelect">
              <option value=''>Select a day</option>
              <% FormFieldData::FREE_DAYS.each do |day| %>
                <option value='<%= day %>'><%= day %></option>
              <% end %>
            </select>
          </div>
          <div class="eight wide column smallSidePadding">
            <select name="free_time[]" class="ui dropdown">
              <option value=''>Select a time</option>
              <% FormFieldData::FREE_TIMES.each do |time| %>
                <option value='<%= time %>'><%= time %></option>
              <% end %>
            </select>
          </div>
        <% end %>
      </div>
    </div>

    <div class="submitButton">
      <p style="color: grey">
        <i class="grey info circle icon"></i>
        Your friends can invite you any time, but, this lets them
        know when you're normally free.
      </p>
      <input type="submit" value="Done" class="ui fluid positive button" />
    </div>
  </form>
</div>

<script type="text/javascript">
  $('select.dropdown').dropdown();
  $('.selection.dropdown').attr('style', 'min-width: 10.5rem');
</script>
<% end %>

app/views/users/friends.html.erb
<style>
  #Friends .container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: .75rem;
  }

  #Friends .image {
    width: 2.5rem;
    height: 2.5rem;
  }

  #Friends .name {
    font-size: 1.3em;
  }
</style>

<div id="Friends" class="ui segment">
<% unless @friends.present? %>
  <div style="text-align: center" class="ui grey message">
    You have no friends using Let's Thryve. Invite some!
  </div>
<% end %>
<% @friends.each do |friend| %>
  <div class="container">
    <img class="ui avatar image" src="<%= friend.picture_url %>">
    <span class="name"><%= friend.full_name %></span>
    <a class="ui icon button" href="<%= user_activity_path(friend) %>">
      <i class="chevron right icon"></i>
    </a>
  </div>
<% end %>
</div>

app/views/users/goals.html.erb
<%= render 'users/profile_tabs' %>
<style>
  #NewGoal > .info {
    text-align: center;
    font-size: 1.3rem;
    margin-bottom: 1rem;
  }

  #GoalList .goal > .description {
    padding-top: .75rem;
    margin-bottom: .75rem;
  }

  #GoalList .goal > .goalButtons {
    display: flex;
    justify-content: space-between;
  }

  #GoalList .goal > .goalButtons > button {
    width: 30%;
  }

  #GoalList .encouragedCount {
    color: #2185D0;
  }

  #GoalList .message {
    text-align: center;
  }
</style>
<% if @user.id == @current_user.id %>
  <div id="NewGoal" class="ui segment">
    <div class="info">
      Create a New Goal
    </div>
    <form method="post" action="/new_goal" class="ui form">
      <div class="field">
        <textarea name="goalText" placeholder="What's your goal?" rows="2"></textarea>
      </div>
      <p style="color: grey;">
        <i class="grey info circle icon"></i>
        Your friends will be able to see your goals and encourage you!
        Don't let them down!
      </p>
      <input type="submit" value="Done" class="ui positive fluid button" />
    </form>
  </div>
<% end %>
<div id="GoalList">
  <% unless @goals.present? %>
    <div style="text-align: center" class="ui grey message">
      There are no goals set?! Come on, thryve!
    </div>
  <% end %>
  <% @goals.each do |goal| %>
    <div class="ui segment goal">
      <a class="ui ribbon label">Goal started <%= goal.created_at.strftime('%b %e, %Y') %></a>
      <div class="description"><%== goal.text %></div>

      <% unless goal.goal_encouragements.count == 0 %>
        <div class="ui styled fluid accordion">
          <div class="title">
            <i class="dropdown icon"></i>
            <span class="encouragedCount"><%= pluralize(goal.goal_encouragements.count, 'person') %> <%= goal.goal_encouragements.count == 1 ? 'has' : 'have' %> encouraged <%= (@user == @current_user) ? 'you' : @user.first_name %></span>
          </div>
          <div class="content">
            <% goal.goal_encouragements.each do |e| %>
              <p>
                <img class="ui avatar image" src="<%= e.user.picture_url %>" />
                <span><%== e.text %></span>
              </p>
            <% end %>
          </div>
        </div>
      <% end %>

      <div style="margin-top: .75rem"></div>

      <% if @user == @current_user && goal.state == 3 %>
      <div class="goalButtons">
        <%= link_to 'Did it!', log_goal_path(goal, state: 2), class: 'ui green button' %>
        <%= link_to 'Tried', log_goal_path(goal, state: 1), class: 'ui lightgrey button' %>
        <%= link_to 'Didn\'t', log_goal_path(goal, state: 0), class: 'ui red button' %>
      </div>
      <% elsif goal.state == 3 %>
        <form method="post" action="<%= encourage_path(goal) %>">
          <div class="ui fluid action input">
            <input name="message" type="text" placeholder="Encourage <%= @user.first_name %>!">
            <button type="submit" class="ui green button">Encourage</button>
          </div>
        </form>
      <% else %>
        <div class="ui <%= ['red', 'grey', 'green'][goal.state] %> message"><%= @user.first_name %> <%= Goal::GOAL_ACTIONS[goal.state] %> - <%= goal.updated_at.strftime('%b %e') %></div>
      <% end %>
    </div>
  <% end %>
</div>



<script>
  $('select.dropdown').dropdown();
  $('.ui.accordion').accordion();
</script>

app/views/users/interests.html.erb
<%= render 'users/profile_tabs' %>

<style type="text/css">
  #InterestList {
    width: 90%;
    margin: auto;
  }

  #InterestList > p {
    margin-top: .75rem;
  }

  #webview-content .activity {
    margin-bottom: .25rem;
  }

  #webview-content .labelText {
    width: 6.5rem;
    font-size: .9rem;
  }

  #interestCards .column {
    margin-bottom: 0.25rem;
  }
</style>

<% unless @edit_mode %>
<div id="InterestList" class="ui raised segment">
  <a class="ui red ribbon label">Exercising</a>
  <p>
    <% @interests[:exercises].each do |interest| %>
      <span class="ui label"><%= interest %></span>
    <% end %>
  </p>
  <a class="ui teal left ribbon label">Hanging Out</a>
  <p>
    <% @interests[:hangouts].each do |interest| %>
      <span class="ui label"><%= interest %></span>
    <% end %>
  </p>
  <a class="ui blue left ribbon label">Campus Events</a>
  <p>
    <% @interests[:oncampus].each do |interest| %>
      <span class="ui label"><%= interest %></span>
    <% end %>
  </p>

  <% if @user == @current_user %>
    <%= link_to 'Edit', edit_interests_path, class: 'ui lightgrey fluid button' %>
  <% end %>
</div>
<% else %>
<div id="webview-content">
  <div class="infoContainer">
    <p style="font-size: 1.1rem">What are your favorite things to do together?</p>
  </div>
  <form class="ui form" action="/set_interests" method="post">
    <div class="ui labeled input activity">
      <div class="ui label labelText">Exercise</div>
      <select multiple class="ui dropdown flushBorder" name="exercises[]">
        <option value=''>Select all that apply</option>
        <% FormFieldData::EXERCISE.each do |activity| %>
          <option value="<%= activity %>"><%= activity %></option>
        <% end %>
      </select>
    </div>
    <div class="ui labeled input activity">
      <div class="ui label labelText">Hang Out</div>
      <select multiple class="ui dropdown flushBorder" name="hangouts[]">
        <option value=''>Select all that apply</option>
        <% FormFieldData::HANGOUT.each do |activity| %>
          <option value="<%= activity %>"><%= activity %></option>
        <% end %>
      </select>
    </div>
    <div class="ui labeled input activity">
      <div class="ui label labelText">On Campus</div>
      <select multiple class="ui dropdown flushBorder" name="oncampus[]">
        <option value=''>Select all that apply</option>
        <% FormFieldData::ONCAMPUS.each do |activity| %>
          <option value="<%= activity %>"><%= activity %></option>
        <% end %>
      </select>
    </div>

    <div class="submitButton">
      <p style="color: grey">
        <i class="grey info circle icon"></i>
        Your friends can invite you to any activity, but, this lets them
        know what you <strong>really</strong> love to do!
      </p>
      <input type="submit" value="Done" class="ui positive fluid button" />
    </div>
  </form>
</div>


<script type="text/javascript">
  $('select.dropdown').dropdown();
  $('.selection.dropdown').attr('style', 'width: 16rem');
</script>
<% end %>

app/views/users/login_success.html.erb
<script>
  window.extAsyncInit = function() {
    MessengerExtensions.requestCloseBrowser(function success() {
      console.log('window closed!');
    }, function error(err) {
      console.log('Attempting to close window with window.close()');
      window.close();
    });
  };
</script>

<script>
(function(d, s, id){
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.com/en_US/messenger.Extensions.js";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'Messenger'));
</script>

app/views/users/newsfeed.html.erb
<style>
  #NewsfeedMenu > .item {
    min-width: 50%;
  }

  #NewsfeedMenu > .item > span {
    margin: auto;
  }
</style>

<div id="NewsfeedMenu" class="ui blue secondary pointing menu">
  <a href="<%= user_newsfeed_path %>" class="item <%= 'active' unless @show_all %>">
    <span>Just Friends</span>
  </a>
  <a href="<%= user_newsfeed_path(show_all: true) %>" class="item <%= 'active' if @show_all %>">
    <span>All Campus</span>
  </a>
</div>

<%= render 'users/activity_list' %>