config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  get 'messages/webhook', to: 'messages#webhook'
  post 'messages/webhook', to: 'messages#incoming'

  # Force login endpoint
  get '/force_login/:name', to: 'users#force_login'

  # Facebook oauth endpoint
  get '/login_success', to: 'users#login_success'

  # User newsfeed and profile stuff
  get '/newsfeed', to: 'users#newsfeed', as: :user_newsfeed
  get '/friends', to: 'users#friends', as: :user_friends
  get '/users/:user_id/activity', to: 'users#activity', as: :user_activity

  get '/users/:user_id/goals', to: 'users#goals', as: :user_goals
  post '/new_goal', to: 'users#new_goal', as: :new_goal
  post '/goal/:goal_id/encourage', to: 'users#encourage', as: :encourage
  get '/goal/:goal_id/log', to: 'users#log_goal', as: :log_goal

  get '/users/:user_id/availability', to: 'users#availability', as: :user_availability
  get '/edit_availability', to: 'users#edit_availability', as: :edit_availability
  post '/set_availability', to: 'users#set_availability', as: :set_availability

  get '/users/:user_id/interests', to: 'users#interests', as: :user_interests
  get '/edit_interests', to: 'users#edit_interests', as: :edit_interests
  post '/set_interests', to: 'users#set_interests', as: :set_interests

  # Invites
  get '/invites/new', to: 'invites#new', as: :new_invite
  post '/invites/create', to: 'invites#create', as: :create_invite
  get '/invites/upcoming', to: 'invites#upcoming', as: :upcoming_invites
  get '/invites/respond', to: 'invites#respond', as: :respond_invite
  post '/invites/:id/accept', to: 'invites#accept', as: :accept_invite
  post '/invites/:id/decline', to: 'invites#decline', as: :decline_invite

end

app/views/layouts/_menu.html.erb
<style>
  #MainMenu .item {
    flex-grow: 1;
  }
</style>

<div id="MainMenu" class="ui pointing menu">
  <%= link_to 'Newsfeed', user_newsfeed_path, class: "item #{'active' if current_page?(user_newsfeed_path)}" %>
  <%= link_to 'Myself', user_activity_path(@current_user), class: "item #{'active' if current_page?(user_activity_path(@current_user)) || current_page?(user_goals_path(@current_user)) || current_page?(user_interests_path(@current_user)) || current_page?(user_availability_path(@current_user)) || current_page?(edit_availability_path) || current_page?(edit_interests_path)}" %>
  <%= link_to 'Friends', user_friends_path, class: "item #{'active' if current_page?(user_friends_path) || (@user.present? && @user != @current_user)}" %>
  <%= link_to 'Invite', new_invite_path, class: "item #{'active' if current_page?(new_invite_path) || current_page?(upcoming_invites_path)}" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Thryve</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.js"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/bare.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Thryve</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/webview.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Thryve</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.js"></script>
  </head>
  <body>
    <style>
      #MainContainer {
        width: 22.5rem;
        margin: auto;
        margin-bottom: 4rem;
      }
    </style>
    <div id="MainContainer">
      <%= render 'layouts/menu' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/webview_no_menu.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Thryve</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.js"></script>
  </head>
  <body>
    <style>
      #MainContainer {
        width: 22.5rem;
        margin: auto;
        margin-bottom: 4rem;
      }
    </style>
    <div id="MainContainer">
      <%= yield %>
    </div>
  </body>
</html>